import { StyleSheet } from "react-native";
export const guestPageStyle = StyleSheet.create({
  background: {
    position: "relative",
    backgroundColor: "#2F303A",
    flex: 1,
    alignSelf: "stretch",
  },

  guestImage: {
    position: "absolute",
    width: 210,
    height: 324,
    bottom: 0,
    left: 0,
  },
  greenCircle: {
    position: "absolute",
    backgroundColor: "rgba(37, 167, 65, 0.1)",
    width: 300,
    height: 300,
    left: "69.72%",
    top: "60.74%",
    borderRadius: 150,
  },
  blueCircle: {
    position: "absolute",
    backgroundColor: "rgba(11, 138, 255, 0.1)",
    width: 220,
    height: 220,
    left: "33.26%",
    top: "5.76%",
    borderRadius: 110,
  },
  redCircle: {
    position: "absolute",
    backgroundColor: "rgba(143, 48, 134, 0.1)",
    width: 180,
    height: 180,
    left: "0%",
    top: "72.3%",
    borderRadius: 90,
  },
  titleStyle: {
    position: "absolute",
    fontSize: 40,
    fontFamily: "Roboto",
    top: "25%",
    color: "#FFFFFF",
    alignSelf: "center",
  },
  subTitleStyle: {
    flex: 0.7,
    flexWrap: "wrap",
    position: "absolute",
    fontSize: 20,
    width: "75%",
    fontFamily: "Roboto",
    top: "33%",
    left: "14%",
    color: "#FFFFFF",
    textAlign: "center",
  },
  signInButtonPos: {
    top: "8%",
    left: "75%",
    width: "25%",
  },
  signInButtonStyle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    fontFamily: "Roboto",
  },
  signUpButtonPos: {
    top: "47%",
    left: "56%",
    width: "38%",
    height: "10%",
    backgroundColor:
      "linear-gradient(180deg, rgba(11, 138, 255, 0.51) 99.99%, rgba(11, 108, 255, 0) 100%)",

    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
  },
  signUpButtonStyle: {
    padding: "9%",
    flex: 1,
    alignSelf: "center",
    fontSize: 24,
    color: "#FFFFFF",
  },
});
